---
title: "Data Import"
output: github_document
---
```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Lets read in a csv file. 

```{r}
litters_df =
  read_csv("./data/FAS_litters.csv")
```


```{r}
names(litters_df)
```

```{r}
litters_df = janitor::clean_names(litters_df)
names(litters_df)
```

Sometimes skimming data is neat?
```{r}
skimr::skim(litters_df)
```


## Import pups data

```{r}
pups_df = 
    read_csv("./data/FAS_pups.csv",
        na = c(".", "NA"), col_types = "fddddd")

pups_df = 
    janitor::clean_names(pups_df)

skimr::skim(pups_df)
```

## Excel formats

CSVs are great but sometimes you get an excel file. 

```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

Import LotR word counts.

```{r}
fotr_df=
    read_excel("data/LOTR_Words.xlsx", range="B3:D6")
```

## SAS dataset import

import the pulse dataset

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")

pulse_df = 
  janitor::clean_names(pulse_df)

```

## Why do i hate read.csv so much
```{r eval = FALSE}
litters_df_base = 
  read.csv("data/FAS_litters.csv")
```

## what about data export

```{r}
write_csv(fotr_df, "data/fotr_df.csv")

```

