---
title: "tidy_data"
output: github_document
date: "2025-09-23"
---

```{r - loading tidyverse}
library(tidyverse)
library(readxl)
library(haven)
```

This document will show how to tidy data.

## Pivot longer

```{r - }
pulse_df = 
  read_sas("dataset/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m, #making these to long
    names_to = "visit", 
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  mutate(visit=replace(visit, visit == "bl", "00m")) |> 
  relocate(id, visit)
  
  
```


Do one more example

```{r}

litters_df =
  read_csv("dataset/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
  ) |> 
  mutate(gd_time = case_match(
    gd_time,
    "gd0_weight" ~ 0,
    "gd18_weight" ~ 18
  ))

```


## Pivot wider

Lets make an analysis table

```{r}
analysis_df =
  tibble(group = c("treatment", "treatment", "control", "control"),
         time = c("pre", "post", "pre", "post"),
         mean= c(4, 10, 4.2, 5))
```

pivot wider - making data 2x2 table

```{r}
analysis_df |> 
  pivot_wider(
    names_from = time,
    values_from = mean
  ) |> 
  knitr::kable()
```


## Bind tables

This is when you want to stack datasets

```{r}

fellowship_ring = 
  read_excel("dataset/LotR_Words.xlsx", range = "B3:D6") |> 
  mutate(movie = "fellowship_ring")

two_towers = 
  read_excel("dataset/LotR_Words.xlsx", range = "F3:H6") |> 
  mutate(movie = "two_towers")

return_king = 
  read_excel("dataset/LotR_Words.xlsx", range = "J3:L6") |> 
  mutate(movie = "return_king")


lotr_df =
  bind_rows(fellowship_ring, two_towers, return_king) |> 

# but above still isn't tidy bc you have variable encoded in the column of sex
  janitor::clean_names() |> 
  pivot_longer(
    cols = female:male,
    names_to = "sex",
    values_to = "words"
    
  ) |> 

#now the above is tidy but can do some extra steps

  relocate(movie) |> 
  mutate(race = str_to_lower(race))
  
```


## Join FAS datasets

Import `litters` dataset.

```{r}
litters_df =
read_csv("dataset/FAS_litters.csv", na=c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  mutate(wt_gain = gd18_weight - gd0_weight) |> 
  separate(
    group, into = c("dose", "day_of_treatment"), sep = 3 # the sep argument tells R to seperate the value after 3rd letter
  )

#non tidyness bc multiple pieces of info in cell

```

IMport `pups` dataset.
```{r}
pups_df =
read_csv("dataset/FAS_pups.csv", na=c("NA", ".", ""), skip = 3) |>
  janitor::clean_names() |> 
  mutate(
    sex = case_match(
      sex, 
      1 ~ "male", 
      2 ~ "female"
    )
  )
```

Join the datasets

```{r}
# want to keep every obs in pups dataframe and add the litters info to the pups dataframe

# R will automatically join by variable it thinkgs is correct, but we should always add by argument

fas_df=
  left_join(pups_df, litters_df, by = "litter_number") |> 
  relocate(litter_number, dose, day_of_treatment)


```

testing if this commits to github